apiVersion: v1
kind: Pod
metadata:
  name: init-container
  namespace: default
spec:
  initContainers:
  - name: install
    image: ubuntu
    command: ["sh", "-c", "apt-get update; apt-get install net-tools -y; apt-get install sudo -y; sudo apt-get update; sudo apt-get install vim -y; sudo apt-get install nano -y; sudo apt-get install openssh-client -y; sudo apt install openssh-server -y;"]
    volumeMounts:
    - name: workdir
      mountPath: /data
  containers:
  - name: mynginx
    image: nginx
    ports:
      - containerPort: 80
    volumeMounts:
    - name: workdir
      mountPath: /usr/share/nginx/html
  volumes:
  - name: workdir
    emptyDir: {}

