apiVersion: v1
kind: Pod
metadata:
  name: sidecarcontainer
  namespace: default
spec:
  volumes:
  - name: logs
    emptyDir: {}
    
  containers:
  - name: mynginx
    image: nginx
    volumeMounts:
    - name: logs
      mountPath: /var/log
    command: ["/bin/sh"]
    args: ["-c", "while true; do date >> /var/log/date.txt; sleep 10; done"]

