apiVersion: v1
kind: Pod
metadata:
  name: ambassador-container
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-conf
      mountPath: /etc/nginx/nginx.conf
      subPath: nginx.conf  # Mount only the specific file from the ConfigMap
    # Add other main application configurations here.

  - name: redis-ambassador
    image: redis
    command: ["redis-server", "--port", "6379"]
    ports:
    - containerPort: 6379

  volumes:
  - name: nginx-conf
    configMap:
      name: nginx-configmap

