apiVersion: v1
kind: Pod
metadata:
  name: namespace-pod-01
  namespace: sampath-ns
  annotations:
    resourcequota.k8s.io/quota1: true  
spec:
  containers:
  - name: myubuntu
    image: ubuntu
    command:
      - sleep
      - "3600"
    resources:
      requests:
        cpu: "100m"
        memory: "100Mi"
        ephemeral-storage: "1Gi"
      limits:
        cpu: "200m"
        memory: "200Mi"
        ephemeral-storage: "2Gi"


















/*
apiVersion: v1 
kind: Pod
metadata:
  name: namespace-pod-01
  namespace: sampath-ns
  resourcequotas: quota1
spec:
  containers:
  - name: myubuntu
    image: ubuntu
    command:
      - sleep
      - "3600"
    resources:
      requests:
        cpu: "100m"
        memory: "100Mi"
        ephemeral-storage: "1Gi"
      limits:
        cpu: "200m"
        memory: "200Mi"
        ephemeral-storage: "2Gi"
 */       
        
#     
#limits.cpu                  200m   400m
#limits.ephemeral-storage    2Gi    4Gi
#limits.memory               200Mi  400Mi
#requests.cpu                100m   200m
#requests.ephemeral-storage  1Gi    2Gi
#requests.memory             100Mi  200Mi
#
