---
apiVersion: v1 
kind: Pod
metadata:
  name: namespace-pod-04
  namespace: sampath-ns
spec:
  containers:
  - name: myubuntu
    image: ubuntu
    command:
      - sleep
      - "3600"
    resources:
      requests:
        cpu: "100m"
        memory: "100Mi"
#        ephemeral-storage: "1Gi"
      limits:
        cpu: "200m"
        memory: "200Mi"  
#        ephemeral-storage: "2Gi"

