apiVersion: v1
kind: Pod
metadata:
  name: default-cpu-demo-3
  namespace: sampath-ns    
spec:
  containers:
  - name: default-cpu-demo-3-ctr
    image: nginx
    resources:
      requests:
        cpu: "0.75"
