kind: Deployment
apiVersion: apps/v1
metadata:
  name: deployments
  namespace: sampath-ns
spec:
  replicas: 3
  selector:      
    matchLabels:
     objtype: deployment
  template:
    metadata:
      name: testpod8
      labels:
        objtype: deployment
    spec:
     containers:
       - name: c00
         image: ubuntu
         command: ["/bin/bash", "-c", "while true; do echo Technical-Guftgu; sleep 5 ; done"]
         resources:
            requests:
              cpu: "50m"
              memory: "50Mi"
              ephemeral-storage: "0.5Gi"
            limits:
              cpu: "100m"
              memory: "100Mi"
              ephemeral-storage: "1Gi"              
