---
apiVersion: v1
kind: Pod
metadata:
  name: quota-01
  namespace: sampath-ns
spec:
  containers:
    - name: myquota-01
      image: nginx
      command:
        - sleep
        - "3600"
      resources:
        requests:
          memory: "64Mi"
          cpu: "100m"
          ephemeral-storage: "5Gi"
        limits:
          memory: "128Mi"
          cpu: "200m"
          ephemeral-storage: "10Gi"

