# read only file system added to this pod at container level
apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo-04
  namespace: default
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 2000
    fsGroup: 3000
  containers:
  - name: myubuntu
    image: ubuntu
    command:
      - sleep
      - "3600"
    securityContext:
      readOnlyRootFilesystem: true
    resources:
      requests:
        cpu: "100m"
        memory: "100Mi"
      limits:
        cpu: "200m"
        memory: "200Mi"
