# security context at pod level and container level also 
# pod as security context 
# and one container as seperate security context 
apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo-02
  namespace: default
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  volumes:
    - name: mynginx-volume
      emptyDir: {}
  containers:
    - name: mynginx
      image: nginx
      command:
        - sleep
        - "3600"
      resources:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "128Mi"
          cpu: "200m"
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
 #       fsGroup: 2000   
    - name: myubuntu
      image: ubuntu
      command:
        - sleep
        - "3600"
      resources:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "128Mi"
          cpu: "200m"          
