# run as root added to this pod at container level
apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo-06
  namespace: default
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 2000
    fsGroup: 3000
  volumes:
  -  name: sampath
     emptyDir: {}
  containers:
  - name: myubuntu
    image: ubuntu
    command:
      - sleep
      - "3600"
    volumeMounts:
    -  name: sampath
       mountPath: /data/demo
    securityContext:
        allowPrivilegeEscalation: false
    resources:
      requests:
        cpu: "100m"
        memory: "100Mi"
      limits:
        cpu: "200m"
        memory: "200Mi"
