apiVersion: v1
kind: Pod
metadata:
  name: sidecarcontainer
  namespace: default
spec:
  volumes:
  - name: logs
    emptyDir: {}
  containers:
  - name: mybusybox
    image: busybox
    volumeMounts:
    - name: logs
      mountPath: /var/log
    command: ["/bin/sh"]
    args: ["-c", "while true; do date >> /var/log/date.txt; sleep 10; done"]
    ports:
    - containerPort: 80   

    volumeMounts:
    - name: logs
      mountPath: /var/www/html
